<?php

use Drupal\Core\Render\Element;
use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * This is the file description for the Label Help module.
 *
 * In normal rendering of textarea form fields that are text-format-enabled,
 * the field's help text gets placed below the text format selector and tips.
 * This means that website users are unlikely to notice and read the help text.
 * This module creates help text to be placed directly below the field's
 * label.
 */

/**
 * Implements hook_form_alter().
 */
function label_help_form_alter(&$form, &$form_state, $form_id) {
  $children = array_intersect_key($form, array_flip(Element::children($form)));
  foreach ($children as $key => $item) {
    
    $form_object = $form_state->getFormObject();
    if (!method_exists($form_object, 'getEntity')){ 
      continue;
    }
    $form_entity = $form_object->getEntity();
    if (!method_exists($form_entity, 'getFieldDefinition')) {
      continue;
    }
    $method = new ReflectionMethod($form_entity, 'getFieldDefinition');
    if(!$method->isPublic()) {
      continue;
    }
    $form_entity_get_field_definition_method = new ReflectionMethod($form_entity, 'getFieldDefinition');
    $field = $form_object->getEntity()->getFieldDefinition($key);

    $label_help = NULL;
    $label_help_mapping = NULL;
    if (method_exists($field, 'getThirdPartySetting')) {
      $label_help = $field->getThirdPartySetting('label_help', 'label_help_description');
      $label_help_mapping = $field->getThirdPartySettings('label_help', 'label_help_ecat'); //not sure why this returs and array but im rolling with it
    }
dpm($label_help, "help fheader");
dpm($label_help_mapping,"label mapping");
    if (!is_null($label_help) || (!empty($label_help_mapping && !is_null($label_help_mapping)))) {
dpm("entered");
      // Put comments above the label for field forms of type 'container'
      // that are specifically configured.
      if (isset($item['#type']) && $item['#type'] == 'container') {
        // For reasons best known to the lunatics who designed the Forms API,
        // $form[$key][$item['#language']][0]['#theme_options'] has to be set to get
        // this working for textarea fields, and
        // form[$key][$item['#language']][0]['value']['#theme_options'] has to be set
        // to get this working for one-line text fields, and
        // form[$key][$item['#language']][0]['default']['#theme_options'] has to be set
        // to get this working for some other fields.
	$label_help_markup = "";
        $label_help_markup .= t('<div class="description label-description">@label_help</div>', ['@label_help' => $label_help]);
        
        //add colour for field mappings
	$label_help_markup .= t('<div class="ga_label-field-mappings">'); //style="color:#99ddff; font:bold; padding-left:80px;">');
        
        //build string to display   
        if(array_key_exists('label_help_pd', $label_help_mapping))
          $label_help_markup .= t('<div class="description label-pd">Product description -> @label_help_pd</div>', ['@label_help_pd' => $label_help_mapping['label_help_pd']]);
        if(array_key_exists('label_help_pmp', $label_help_mapping))
          $label_help_markup .= t('<div class="description label-pmp">Project management plan -> @label_help_pmp</div>', ['@label_help_pmp' => $label_help_mapping['label_help_pmp']]);
        if(array_key_exists('label_help_ecat', $label_help_mapping))
          $label_help_markup .= t('<div class="description label-ecat">eCat -> @label_help_ecat</div>', ['@label_help_ecat' => $label_help_mapping['label_help_ecat']]);
        if(array_key_exists('label_help_nci', $label_help_mapping))
          $label_help_markup .= t('<div class="description label-nci">NCI -> @label_help_nci</div>', ['@label_help_nci' => $label_help_mapping['label_help_nci']]);
        if(array_key_exists('label_help_cf', $label_help_mapping))
          $label_help_markup .= t('<div class="description label-cf">CF -> @label_help_cf</div>', ['@label_help_cf' => $label_help_mapping['label_help_cf']]);
        $label_help_markup .= t('</div>');


 ksm($form[$key]['widget'], "widget: ");
        //add build string to the correct field type
        if (isset($form[$key]['widget'][0]['value'])) {
          $form[$key]['widget'][0]['value']['#label_suffix'] = $label_help_markup;
	dpm($key, "key1");
        }
        elseif (isset($form[$key]['widget'][0]['#title'])) {
          $form[$key]['widget'][0]['#label_suffix'] = $label_help_markup;
	dpm($key, "key2");
        }
        elseif (isset($form[$key]['widget']['#title'])) {
	  if(isset($form[$key]['widget']['#suffix'])){
            $form[$key]['widget']['#suffix'] = $label_help_markup.$form[$key]['widget']['#suffix'];
	    dpm($key, "key3");
          } else {
	   $form[$key]['widget'][0]['target_id']['#description'] = $label_help_markup.$form[$key]['widget'][0]['target_id']['#description'] ;
	   dpm($key, "key 3.5");
          }
        }
        elseif (isset($form[$key]['widget']['target_id']['#title'])) {
          $form[$key]['widget']['target_id']['#label_suffix'] = $label_help_markup;
	dpm($key, "key4");
        }
        // One more for cshs module.
//        elseif (isset($form[$key][$item['#language']][0]['tid'])) {
//          $form[$key][$item['#language']][0]['tid']['#theme_options'] = $theme_option;
//        }
      }
 ksm($form[$key]['widget'], "widget check: ");
    } else {
dpm("skip");
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */

function label_help_form_field_config_edit_form_alter(&$form, &$form_state, $form_id) {
  $fieldConfig = $form_state->getFormObject()->getEntity();
  // Add settings for file upload widgets.
  $form['settings']['label_help_description'] = array(
    '#type' => 'textarea',
    '#rows' => 5,
    '#title' => t('Header field Label'),
    '#default_value' => $fieldConfig->getThirdPartySetting('label_help', 'label_help_description'),
    '#description' => t('Help text to insert below the label and above the input form element.'),
  );
  
  $form['settings']['label_help_mapping'] = array(
    '#type' => 'fieldset',
    '#title' => t('Field mapping'),
    '#collapsible' => TRUE, // Added
    '#collapsed' => TRUE,  // Added
   );

  $form['settings']['label_help_mapping']['pd'] = array(
    '#type' => 'textarea',
    '#rows' => 1,
    '#title' => t('Project description'),
    '#default_value' => $fieldConfig->getThirdPartySetting('label_help', 'label_help_pd'),
    '#description' => t('Help text to insert below the label and above the input form element.'),
  );

  $form['settings']['label_help_mapping']['pmp'] = array(
    '#type' => 'textarea',
    '#rows' => 1,
    '#title' => t('Project management plan'),
    '#default_value' => $fieldConfig->getThirdPartySetting('label_help', 'label_help_pmp'),
    '#description' => t('Help text to insert below the label and above the input form element.'),
  );

  $form['settings']['label_help_mapping']['ecat'] = array(
    '#type' => 'textarea',
    '#rows' => 1,
    '#title' => t('eCat'),
    '#default_value' => $fieldConfig->getThirdPartySetting('label_help', 'label_help_ecat'),
    '#description' => t('Help text to insert below the label and above the input form element.'),
  );

  $form['settings']['label_help_mapping']['nci'] = array(
    '#type' => 'textarea',
    '#rows' => 1,
    '#title' => t('NCI'),
    '#default_value' => $fieldConfig->getThirdPartySetting('label_help', 'label_help_nci'),
    '#description' => t('Help text to insert below the label and above the input form element.'),
  );

  $form['settings']['label_help_mapping']['cf'] = array(
    '#type' => 'textarea',
    '#rows' => 1,
    '#title' => t('CF'),
    '#default_value' => $fieldConfig->getThirdPartySetting('label_help', 'label_help_cf'),
    '#description' => t('Help text to insert below the label and above the input form element.'),
  );

  $form['#entity_builders'][] = 'label_help_form_field_config_edit_form_builder';
}

/**
 * Entity builder for the menu configuration entity.
 */
function label_help_form_field_config_edit_form_builder($entity_type, $field, &$form, FormStateInterface $form_state) {
  if ($form_state->getValue(['settings', 'label_help_description'])) {
    $field->setThirdPartySetting('label_help', 'label_help_description', $form_state->getValue(['settings', 'label_help_description']));
    //return;
  }
  else{
    $field->unsetThirdPartySetting('label_help', 'label_help_description');
  }
  if ($form_state->getValue(['settings', 'label_help_mapping', 'pd'])) {
    $field->setThirdPartySetting('label_help', 'label_help_pd', $form_state->getValue(['settings', 'label_help_mapping', 'pd']));
  }
  else{
    $field->unsetThirdPartySetting('label_help', 'label_help_pd');
  }
  if ($form_state->getValue(['settings', 'label_help_mapping', 'pmp'])) {
    $field->setThirdPartySetting('label_help', 'label_help_pmp', $form_state->getValue(['settings', 'label_help_mapping', 'pmp']));
  }
  else{
    $field->unsetThirdPartySetting('label_help', 'label_help_pmp');
  }
  if ($form_state->getValue(['settings', 'label_help_mapping', 'ecat'])) {
    $field->setThirdPartySetting('label_help', 'label_help_ecat', $form_state->getValue(['settings', 'label_help_mapping', 'ecat']));
  }
  else{
    $field->unsetThirdPartySetting('label_help', 'label_help_ecat');
  }
  if ($form_state->getValue(['settings', 'label_help_mapping', 'nci'])) {
    $field->setThirdPartySetting('label_help', 'label_help_nci', $form_state->getValue(['settings', 'label_help_mapping', 'nci']));
  }
  else{
    $field->unsetThirdPartySetting('label_help', 'label_help_nci');
  }
  if ($form_state->getValue(['settings', 'label_help_mapping', 'cf'])) {
    $field->setThirdPartySetting('label_help', 'label_help_cf', $form_state->getValue(['settings', 'label_help_mapping', 'cf']));
  }
  else{
    $field->unsetThirdPartySetting('label_help', 'label_help_cf');
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function label_help_preprocess_form_element(&$variables) {
  if (!isset($variables['element']['#name'])) {
    return;
  }
  // setting a label suffix/prefix
  $element = &$variables['element'];
  if (!empty($variables['label'])) {
    if (!empty($element['#label_prefix'])) {
      $variables['label']['#prefix'] = $element['#label_prefix'];
    }
    if (!empty($element['#label_suffix'])) {
      $variables['label']['#suffix'] = $element['#label_suffix'];
    }
  }
}

